import { useNavigate } from 'react-router-dom'
import useSWR from 'swr'
import { healthCheck } from '../services/api'
import { useAuth } from '../context/AuthContext'
import RecentTasks from './RecentTasks'

function MainContent() {
  const navigate = useNavigate()
  const { user } = useAuth()
  const { data, error } = useSWR('health', healthCheck, { revalidateOnFocus: false })
  const backendConnected = data?.status === 'ok' && !error

  return (
    <main className="dashboard">
      <section className="dashboard-header">
        <div>
          <p className="eyebrow">SOVEREIGN AI WORKBENCH</p>
          <h1>Welcome back.</h1>
          <p className="dashboard-subtitle">
            Signed in as <strong>{user?.role ?? 'unknown'}</strong>. Your requests are routed only to authorized pgvector tiers.
          </p>
        </div>

        <div className="system-status">
          <span className={backendConnected ? 'status-dot online' : 'status-dot'} />
          <span>{error ? 'Backend unavailable' : backendConnected ? 'System online' : 'Checking system'}</span>
        </div>
      </section>

      <section className="task-composer">
        <div>
          <p className="composer-label">START A NEW TASK</p>
          <h2>What would you like Sovereign AI to do?</h2>
          <p>Ask the agent to analyze documents, search authorized knowledge, generate deliverables, or perform a multi-step task.</p>
        </div>

        <button className="new-task-button" onClick={() => navigate('/new-task')}>+ New Task</button>
      </section>

      <section className="dashboard-grid">
        <div className="dashboard-card">
          <p className="card-label">ACCESS LEVEL</p>
          <h3>{user?.role ?? 'Unknown'}</h3>
          <p>Your requests are restricted to knowledge tiers authorized for your role.</p>
        </div>

        <div className="dashboard-card">
          <p className="card-label">KNOWLEDGE BASE</p>
          <h3>Authorized search</h3>
          <p>Search organizational knowledge without exposing data outside your permitted access level.</p>
          <button className="card-action" onClick={() => navigate('/knowledge')}>Search knowledge →</button>
        </div>

        <div className="dashboard-card">
          <p className="card-label">WORKSPACE</p>
          <h3>Tasks &amp; artifacts</h3>
          <p>Track agent jobs and access the deliverables generated by completed tasks.</p>
          <button className="card-action" onClick={() => navigate('/tasks')}>View tasks →</button>
        </div>
      </section>

      <div className="dashboard-recent">
        <RecentTasks />
      </div>
    </main>
  )
}

export default MainContent
