CREATE TABLE IF NOT EXISTS jobs (id VARCHAR(255) PRIMARY KEY, data JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS events (id BIGSERIAL PRIMARY KEY, job_id VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, data JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS approvals (id BIGSERIAL PRIMARY KEY, job_id VARCHAR(255) NOT NULL, approved BOOLEAN NOT NULL, reviewer VARCHAR(255) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS files (id VARCHAR(255) PRIMARY KEY, owner_id VARCHAR(255) NOT NULL, tenant_id VARCHAR(255) NOT NULL, name VARCHAR(512) NOT NULL, path TEXT NOT NULL, metadata JSONB NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS audit_events (id BIGSERIAL PRIMARY KEY, actor_id VARCHAR(255), tenant_id VARCHAR(255), action VARCHAR(255) NOT NULL, resource VARCHAR(255), data JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS job_queue (job_id VARCHAR(255) PRIMARY KEY REFERENCES jobs(id) ON DELETE CASCADE, status VARCHAR(32) NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS events_job_id_idx ON events(job_id, id);
CREATE INDEX IF NOT EXISTS jobs_status_idx ON jobs USING gin(data);